name: Review
on: [pull_request]
jobs:
  eslint:
    name: ESLint check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.REVIEW_TOKEN }}
          reporter: github-pr-review
          eslint_flags: "src/lib/"
          fail_on_error: true
